% UNIT_CONVERTER_UTILS - Comprehensive Unit Conversion Toolbox
% A zero-dependency MATLAB toolbox for converting between various units
% of measurement including length, weight, temperature, area, volume,
% pressure, speed, time, data, and angle.
%
% Main function: unit_converter_utils(value, from_unit, to_unit, category)
%
% Categories:
%   'length'      - meters, km, cm, mm, miles, yards, feet, inches
%   'weight'      - kg, g, mg, lb, oz, tons, tonnes
%   'temperature' - celsius, fahrenheit, kelvin
%   'area'        - m2, km2, cm2, mm2, ha, acre, ft2, in2
%   'volume'      - l, ml, m3, cm3, gal, qt, pt, fl_oz
%   'pressure'    - pa, kpa, mpa, bar, psi, atm, mmhg
%   'speed'       - mps, kmph, mph, knots, fps
%   'time'        - s, ms, us, ns, min, h, day, week, year
%   'data'        - b, kb, mb, gb, tb, pb
%   'angle'       - deg, rad, grad, arcmin, arcsec
%
% Example:
%   result = unit_converter_utils(100, 'km', 'miles', 'length')
%   result = unit_converter_utils(0, 'celsius', 'fahrenheit', 'temperature')
%
% Author: AllToolkit Auto-Generated
% Date: 2026-05-25
% License: MIT

function result = unit_converter_utils(value, from_unit, to_unit, category)
    arguments
        value (1,1) double
        from_unit (1,1) string
        to_unit (1,1) string
        category (1,1) string
    end
    
    % Normalize unit names to lowercase
    from_unit = lower(strtrim(from_unit));
    to_unit = lower(strtrim(to_unit));
    category = lower(strtrim(category));
    
    % Validate inputs
    if ~isnumeric(value) || ~isscalar(value)
        error('unit_converter_utils:InvalidValue', 'Value must be a numeric scalar');
    end
    
    % Dispatch to appropriate conversion function
    switch category
        case 'length'
            result = convert_length(value, from_unit, to_unit);
        case 'weight'
            result = convert_weight(value, from_unit, to_unit);
        case 'temperature'
            result = convert_temperature(value, from_unit, to_unit);
        case 'area'
            result = convert_area(value, from_unit, to_unit);
        case 'volume'
            result = convert_volume(value, from_unit, to_unit);
        case 'pressure'
            result = convert_pressure(value, from_unit, to_unit);
        case 'speed'
            result = convert_speed(value, from_unit, to_unit);
        case 'time'
            result = convert_time(value, from_unit, to_unit);
        case 'data'
            result = convert_data(value, from_unit, to_unit);
        case 'angle'
            result = convert_angle(value, from_unit, to_unit);
        otherwise
            error('unit_converter_utils:UnknownCategory', ...
                'Unknown category: %s. Valid categories: length, weight, temperature, area, volume, pressure, speed, time, data, angle', category);
    end
end

%% LENGTH CONVERSION
function result = convert_length(value, from_unit, to_unit)
    % Conversion factors to meters (base unit)
    factors = struct( ...
        'm', 1, ...
        'meter', 1, ...
        'meters', 1, ...
        'km', 1000, ...
        'kilometer', 1000, ...
        'kilometers', 1000, ...
        'cm', 0.01, ...
        'centimeter', 0.01, ...
        'centimeters', 0.01, ...
        'mm', 0.001, ...
        'millimeter', 0.001, ...
        'millimeters', 0.001, ...
        'mi', 1609.344, ...
        'mile', 1609.344, ...
        'miles', 1609.344, ...
        'yd', 0.9144, ...
        'yard', 0.9144, ...
        'yards', 0.9144, ...
        'ft', 0.3048, ...
        'foot', 0.3048, ...
        'feet', 0.3048, ...
        'in', 0.0254, ...
        'inch', 0.0254, ...
        'inches', 0.0254, ...
        'nm', 1.852e3, ...
        'nautical_mile', 1.852e3, ...
        'nautical_miles', 1.852e3 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'length');
    result = value * from_factor / to_factor;
end

%% WEIGHT CONVERSION
function result = convert_weight(value, from_unit, to_unit)
    % Conversion factors to kilograms (base unit)
    factors = struct( ...
        'kg', 1, ...
        'kilogram', 1, ...
        'kilograms', 1, ...
        'g', 0.001, ...
        'gram', 0.001, ...
        'grams', 0.001, ...
        'mg', 1e-6, ...
        'milligram', 1e-6, ...
        'milligrams', 1e-6, ...
        'lb', 0.45359237, ...
        'pound', 0.45359237, ...
        'pounds', 0.45359237, ...
        'oz', 0.028349523125, ...
        'ounce', 0.028349523125, ...
        'ounces', 0.028349523125, ...
        'ton', 907.18474, ...
        'tons', 907.18474, ...
        'short_ton', 907.18474, ...
        'short_tons', 907.18474, ...
        'tonne', 1000, ...
        'tonnes', 1000, ...
        'metric_ton', 1000, ...
        'metric_tons', 1000, ...
        'long_ton', 1016.0469088, ...
        'long_tons', 1016.0469088 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'weight');
    result = value * from_factor / to_factor;
end

%% TEMPERATURE CONVERSION
function result = convert_temperature(value, from_unit, to_unit)
    % Temperature is special - not a simple multiplication
    % First convert to Celsius, then to target unit
    
    % Normalize unit names
    from_unit = lower(strtrim(from_unit));
    to_unit = lower(strtrim(to_unit));
    
    valid_units = {'c', 'celsius', 'f', 'fahrenheit', 'k', 'kelvin'};
    if ~any(strcmp(from_unit, valid_units)) || ~any(strcmp(to_unit, valid_units))
        error('unit_converter_utils:InvalidTemperatureUnit', ...
            'Invalid temperature unit. Valid units: c, celsius, f, fahrenheit, k, kelvin');
    end
    
    % Convert to Celsius first
    celsius_value = to_celsius(value, from_unit);
    
    % Convert from Celsius to target
    result = from_celsius(celsius_value, to_unit);
end

function celsius = to_celsius(value, from_unit)
    switch from_unit
        case {'c', 'celsius'}
            celsius = value;
        case {'f', 'fahrenheit'}
            celsius = (value - 32) * 5/9;
        case {'k', 'kelvin'}
            celsius = value - 273.15;
        otherwise
            error('unit_converter_utils:InvalidFromUnit', 'Unknown temperature unit: %s', from_unit);
    end
end

function result = from_celsius(celsius, to_unit)
    switch to_unit
        case {'c', 'celsius'}
            result = celsius;
        case {'f', 'fahrenheit'}
            result = celsius * 9/5 + 32;
        case {'k', 'kelvin'}
            result = celsius + 273.15;
        otherwise
            error('unit_converter_utils:InvalidToUnit', 'Unknown temperature unit: %s', to_unit);
    end
end

%% AREA CONVERSION
function result = convert_area(value, from_unit, to_unit)
    % Conversion factors to square meters (base unit)
    factors = struct( ...
        'm2', 1, ...
        'sqm', 1, ...
        'square_meter', 1, ...
        'square_meters', 1, ...
        'km2', 1e6, ...
        'sqkm', 1e6, ...
        'square_kilometer', 1e6, ...
        'square_kilometers', 1e6, ...
        'cm2', 1e-4, ...
        'sqcm', 1e-4, ...
        'square_centimeter', 1e-4, ...
        'square_centimeters', 1e-4, ...
        'mm2', 1e-6, ...
        'sqmm', 1e-6, ...
        'square_millimeter', 1e-6, ...
        'square_millimeters', 1e-6, ...
        'ha', 1e4, ...
        'hectare', 1e4, ...
        'hectares', 1e4, ...
        'acre', 4046.8564224, ...
        'acres', 4046.8564224, ...
        'ft2', 0.09290304, ...
        'sqft', 0.09290304, ...
        'square_foot', 0.09290304, ...
        'square_feet', 0.09290304, ...
        'in2', 6.4516e-4, ...
        'sqin', 6.4516e-4, ...
        'square_inch', 6.4516e-4, ...
        'square_inches', 6.4516e-4, ...
        'yd2', 0.83612736, ...
        'sqyd', 0.83612736, ...
        'square_yard', 0.83612736, ...
        'square_yards', 0.83612736 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'area');
    result = value * from_factor / to_factor;
end

%% VOLUME CONVERSION
function result = convert_volume(value, from_unit, to_unit)
    % Conversion factors to liters (base unit)
    factors = struct( ...
        'l', 1, ...
        'liter', 1, ...
        'liters', 1, ...
        'litre', 1, ...
        'litres', 1, ...
        'ml', 0.001, ...
        'milliliter', 0.001, ...
        'milliliters', 0.001, ...
        'millilitre', 0.001, ...
        'millilitres', 0.001, ...
        'm3', 1000, ...
        'cubic_meter', 1000, ...
        'cubic_meters', 1000, ...
        'cm3', 0.001, ...
        'cubic_centimeter', 0.001, ...
        'cubic_centimeters', 0.001, ...
        'cc', 0.001, ...
        'gal', 3.785411784, ...
        'gallon', 3.785411784, ...
        'gallons', 3.785411784, ...
        'us_gallon', 3.785411784, ...
        'us_gallons', 3.785411784, ...
        'imp_gallon', 4.54609, ...
        'imp_gallons', 4.54609, ...
        'qt', 0.946352946, ...
        'quart', 0.946352946, ...
        'quarts', 0.946352946, ...
        'pt', 0.473176473, ...
        'pint', 0.473176473, ...
        'pints', 0.473176473, ...
        'fl_oz', 0.029573529563, ...
        'fluid_ounce', 0.029573529563, ...
        'fluid_ounces', 0.029573529563, ...
        'cup', 0.2365882365, ...
        'cups', 0.2365882365, ...
        'tbsp', 0.014786764781, ...
        'tablespoon', 0.014786764781, ...
        'tablespoons', 0.014786764781, ...
        'tsp', 0.0049289215938, ...
        'teaspoon', 0.0049289215938, ...
        'teaspoons', 0.0049289215938 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'volume');
    result = value * from_factor / to_factor;
end

%% PRESSURE CONVERSION
function result = convert_pressure(value, from_unit, to_unit)
    % Conversion factors to Pascals (base unit)
    factors = struct( ...
        'pa', 1, ...
        'pascal', 1, ...
        'pascals', 1, ...
        'kpa', 1e3, ...
        'kilopascal', 1e3, ...
        'kilopascals', 1e3, ...
        'mpa', 1e6, ...
        'megapascal', 1e6, ...
        'megapascals', 1e6, ...
        'bar', 1e5, ...
        'bars', 1e5, ...
        'mbar', 100, ...
        'millibar', 100, ...
        'millibars', 100, ...
        'psi', 6894.757293168, ...
        'pound_per_square_inch', 6894.757293168, ...
        'atm', 101325, ...
        'atmosphere', 101325, ...
        'atmospheres', 101325, ...
        'mmhg', 133.322387415, ...
        'torr', 133.322387415, ...
        'inh2o', 249.088908333, ...
        'inch_water', 249.088908333 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'pressure');
    result = value * from_factor / to_factor;
end

%% SPEED CONVERSION
function result = convert_speed(value, from_unit, to_unit)
    % Conversion factors to meters per second (base unit)
    factors = struct( ...
        'mps', 1, ...
        'm/s', 1, ...
        'meter_per_second', 1, ...
        'meters_per_second', 1, ...
        'kmph', 0.277777778, ...
        'km/h', 0.277777778, ...
        'kph', 0.277777778, ...
        'kilometer_per_hour', 0.277777778, ...
        'kilometers_per_hour', 0.277777778, ...
        'mph', 0.44704, ...
        'mile_per_hour', 0.44704, ...
        'miles_per_hour', 0.44704, ...
        'knot', 0.514444444, ...
        'knots', 0.514444444, ...
        'kn', 0.514444444, ...
        'fps', 0.3048, ...
        'ft/s', 0.3048, ...
        'foot_per_second', 0.3048, ...
        'feet_per_second', 0.3048, ...
        'mach', 340.29, ...
        'c', 299792458, ...
        'speed_of_light', 299792458 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'speed');
    result = value * from_factor / to_factor;
end

%% TIME CONVERSION
function result = convert_time(value, from_unit, to_unit)
    % Conversion factors to seconds (base unit)
    factors = struct( ...
        's', 1, ...
        'sec', 1, ...
        'second', 1, ...
        'seconds', 1, ...
        'ms', 1e-3, ...
        'millisecond', 1e-3, ...
        'milliseconds', 1e-3, ...
        'us', 1e-6, ...
        'microsecond', 1e-6, ...
        'microseconds', 1e-6, ...
        'ns', 1e-9, ...
        'nanosecond', 1e-9, ...
        'nanoseconds', 1e-9, ...
        'min', 60, ...
        'minute', 60, ...
        'minutes', 60, ...
        'h', 3600, ...
        'hr', 3600, ...
        'hour', 3600, ...
        'hours', 3600, ...
        'day', 86400, ...
        'days', 86400, ...
        'week', 604800, ...
        'weeks', 604800, ...
        'month', 2629746, ...  % Average month (365.25/12 days)
        'months', 2629746, ...
        'year', 31556952, ...  % Tropical year
        'years', 31556952, ...
        'decade', 315569520, ...
        'decades', 315569520, ...
        'century', 3155695200, ...
        'centuries', 3155695200 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'time');
    result = value * from_factor / to_factor;
end

%% DATA CONVERSION
function result = convert_data(value, from_unit, to_unit)
    % Conversion factors to bytes (base unit)
    % Using binary prefixes (KiB, MiB, etc.) for consistency
    factors = struct( ...
        'b', 1, ...
        'byte', 1, ...
        'bytes', 1, ...
        'kb', 1000, ...
        'kilobyte', 1000, ...
        'kilobytes', 1000, ...
        'kib', 1024, ...
        'kibibyte', 1024, ...
        'kibibytes', 1024, ...
        'mb', 1e6, ...
        'megabyte', 1e6, ...
        'megabytes', 1e6, ...
        'mib', 1048576, ...
        'mebibyte', 1048576, ...
        'mebibytes', 1048576, ...
        'gb', 1e9, ...
        'gigabyte', 1e9, ...
        'gigabytes', 1e9, ...
        'gib', 1073741824, ...
        'gibibyte', 1073741824, ...
        'gibibytes', 1073741824, ...
        'tb', 1e12, ...
        'terabyte', 1e12, ...
        'terabytes', 1e12, ...
        'tib', 1099511627776, ...
        'tebibyte', 1099511627776, ...
        'tebibytes', 1099511627776, ...
        'pb', 1e15, ...
        'petabyte', 1e15, ...
        'petabytes', 1e15, ...
        'pib', 1125899906842624, ...
        'pebibyte', 1125899906842624, ...
        'pebibytes', 1125899906842624, ...
        'bit', 0.125, ...
        'bits', 0.125, ...
        'kbit', 125, ...
        'kilobit', 125, ...
        'kilobits', 125, ...
        'mbit', 125000, ...
        'megabit', 125000, ...
        'megabits', 125000, ...
        'gbit', 125000000, ...
        'gigabit', 125000000, ...
        'gigabits', 125000000 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'data');
    result = value * from_factor / to_factor;
end

%% ANGLE CONVERSION
function result = convert_angle(value, from_unit, to_unit)
    % Conversion factors to degrees (base unit)
    factors = struct( ...
        'deg', 1, ...
        'degree', 1, ...
        'degrees', 1, ...
        'rad', 180/pi, ...
        'radian', 180/pi, ...
        'radians', 180/pi, ...
        'grad', 0.9, ...
        'gon', 0.9, ...
        'gradian', 0.9, ...
        'gradians', 0.9, ...
        'arcmin', 1/60, ...
        'arcminute', 1/60, ...
        'arcminutes', 1/60, ...
        'arcsec', 1/3600, ...
        'arcsecond', 1/3600, ...
        'arcseconds', 1/3600, ...
        'turn', 360, ...
        'turns', 360, ...
        'revolution', 360, ...
        'revolutions', 360, ...
        'circle', 360, ...
        'circles', 360 ...
    );
    
    [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, 'angle');
    result = value * from_factor / to_factor;
end

%% HELPER FUNCTION
function [from_factor, to_factor] = get_factors(factors, from_unit, to_unit, category)
    % Get conversion factors from struct
    from_factor = get_field_safe(factors, from_unit);
    to_factor = get_field_safe(factors, to_unit);
    
    if isempty(from_factor)
        error('unit_converter_utils:InvalidFromUnit', ...
            'Unknown %s unit: %s', category, from_unit);
    end
    if isempty(to_factor)
        error('unit_converter_utils:InvalidToUnit', ...
            'Unknown %s unit: %s', category, to_unit);
    end
end

function value = get_field_safe(s, name)
    % Safely get field value, return empty if not found
    value = [];
    if isfield(s, name)
        value = s.(name);
    end
end

%% UTILITY FUNCTIONS

function list_available_units()
    % Display all available units for each category
    fprintf('\n=== Available Units ===\n\n');
    
    fprintf('LENGTH: m, km, cm, mm, mi, yd, ft, in, nm (nautical mile)\n');
    fprintf('WEIGHT: kg, g, mg, lb, oz, ton, tonne\n');
    fprintf('TEMPERATURE: c/celsius, f/fahrenheit, k/kelvin\n');
    fprintf('AREA: m2, km2, cm2, mm2, ha, acre, ft2, in2, yd2\n');
    fprintf('VOLUME: l, ml, m3, cm3, gal, qt, pt, fl_oz, cup, tbsp, tsp\n');
    fprintf('PRESSURE: pa, kpa, mpa, bar, mbar, psi, atm, mmhg\n');
    fprintf('SPEED: mps, kmph, mph, knots, fps, mach, c (speed of light)\n');
    fprintf('TIME: s, ms, us, ns, min, h, day, week, month, year, decade, century\n');
    fprintf('DATA: b, kb, mb, gb, tb, pb (decimal) or kib, mib, gib, tib, pib (binary)\n');
    fprintf('ANGLE: deg, rad, grad, arcmin, arcsec, turn\n\n');
end

function show_examples()
    % Display usage examples
    fprintf('\n=== Usage Examples ===\n\n');
    
    fprintf('%% Length conversion\n');
    fprintf('unit_converter_utils(100, ''km'', ''miles'', ''length'')\n');
    fprintf('%% Result: 62.137\n\n');
    
    fprintf('%% Temperature conversion\n');
    fprintf('unit_converter_utils(0, ''celsius'', ''fahrenheit'', ''temperature'')\n');
    fprintf('%% Result: 32\n\n');
    
    fprintf('%% Weight conversion\n');
    fprintf('unit_converter_utils(1, ''kg'', ''lb'', ''weight'')\n');
    fprintf('%% Result: 2.2046\n\n');
    
    fprintf('%% Data conversion\n');
    fprintf('unit_converter_utils(1024, ''mib'', ''gib'', ''data'')\n');
    fprintf('%% Result: 1\n\n');
end